[program:taxsage]
command=/home/taxsage/taxsage-api/venv/bin/gunicorn -w 2 -b 0.0.0.0:5003 app:app
directory=/home/taxsage/taxsage-api
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/taxsage.err.log
stdout_logfile=/var/log/taxsage.out.log
