[program:cleansage]
command=/home/cleansage/cleansage/venv/bin/gunicorn -w 2 -b 0.0.0.0:5002 --timeout 120 app:app
directory=/home/cleansage/cleansage
user=cleansage
autostart=true
autorestart=true
startretries=3
stopwaitsecs=10
stderr_logfile=/var/log/cleansage/err.log
stdout_logfile=/var/log/cleansage/out.log
environment=PYTHONUNBUFFERED="1"
